### ISSUE TITLE
An exception occurs when playing music

### ISSUE THREAD

**Issue by Siketyan** [Legato-Dev/Legato-NowPlaying#36]
### Summary
When AIMP was playing music, .NET Framework under Legato caught an exception below.

### How to reproduce
I couldn't find how to reproduce the exception.

### Screenshot
![image](https://user-images.githubusercontent.com/12772118/45231698-dd13b780-b307-11e8-8858-ff50fba1b310.png)

### Stacktrace of the Exception
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Misq.Core.<Request>d__0.MoveNext()
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Misq.Me.<Request>d__13.MoveNext()
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegatoNowPlaying.Services.Misskey.Service.<Post>d__7.MoveNext()
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegatoNowPlaying.Accounts.<Post>d__3.MoveNext()
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegatoNowPlaying.MainForm.<_PostAsync>d__19.MoveNext()
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LegatoNowPlaying.MainForm.<<MainForm_Load>b__24_0>d.MoveNext()
---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by Siketyan** [comment]
I think it is a problem of server of Misskey, but I think Legato should add handling of this exception.

**Comment by marihachi** [comment]
どんなJSONを受け取って、どんな対策を取るべきかが分からないと対処することは難しそう

**Comment by Siketyan** [comment]
そもそもJSONがきてない（サーバエラーしてる）んだけどステータスコード見てる？

**Comment by marihachi** [comment]
そもそも、それぞれのサービス(Twitter、Misskey)のHTTPレイヤーはそれぞれのライブラリによって隠蔽されているので、Legato-NowPlayingで関与すべきことではなさそう。
降ってきた例外を掴んでよしなにするくらいだと思う。

**Comment by marihachi** [comment]
https://github.com/CoreTweet/CoreTweet
https://github.com/syuilo/Misq

**Comment by marihachi** [comment]
なんて例外が飛んできてる？

**Comment by Siketyan** [comment]
いまのところ確認できたのはそれぐらい
CoreTweetがTwitterException投げる要領でMisqもMisskeyExceptionとか投げてくれるといいんだけどね、と思いつつ

**Comment by marihachi** [comment]
ふむ

**Comment by Asteriskx** [comment]
この間の DDoS 攻撃時に起きてたぽいから、
API 介して接続が出来ていないときに例外吐いてそうっていう予想はしてる。
例外は JsonReaderException だけ拾ってるけど、 Siketyan も言ってる通り、
各サービスごとに throw してあげるのもいいのかもしれない。
